Handle stack removal failures
medikoo/serverless-plugin-vpc-eni-cleanup pull request #11
Opened 2022-07-15 16:29 UTC by perrin4869

Haven't tested if this works yet, is this what you meant? @medikoo 
I'll test it later if it works!
Also I went ahead and removed `bluebird`, don't think anyone needs it anymore...

2022-07-15 16:29 UTC, perrin4869 commented
Closes #10

2022-07-15 16:32 UTC, medikoo reviewed
@perrin4869 it looks great, still can you make different PR with blubird removal? Ideally, if two different things are not mixed under one PR (if one raises issues other thing is not blocked)

2022-07-15 17:00 UTC, perrin4869 commented
Of course, it's a bad habit of mine haha
Done!

2022-07-16 08:28 UTC, medikoo requested changes

2022-07-16 08:28 UTC, medikoo commented on index.js
> +			"error:remove:remove": () => (this.isDisabled = true)
It should be just `error` :)

2022-07-16 08:47 UTC, perrin4869 commented on index.js
> +			"error:remove:remove": () => (this.isDisabled = true)
Thanks!

2022-07-16 10:56 UTC, medikoo approved these changes
Thank you@

2022-07-16 10:56 UTC, merged